name: arretai
description: A new Flutter project.
publish_to: 'none'
version: 0.5.0+7

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: ^0.7.2
  font_awesome_flutter: ^8.8.1
  google_fonts: ^1.1.0
  intent: ^1.4.0
  location: ^3.0.2
  pedantic: ^1.9.0
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12
  yaml: ^2.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true

  assets:
    - assets/help.yml
    - assets/images/
    - assets/images/postures/

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon/icon.png'
  adaptive_icon_background: '#00A85A'
  adaptive_icon_foreground: 'assets/images/icon/foreground.png'
